### ISSUE TITLE
Some elements maintain browser styles

### ISSUE THREAD

**Issue by PickJBennett** [nicolas-cusan/destyle.css#1]
Nice work, however I encountered several issues if what I’m understanding you’re trying to do is right (by removing all styles added by the browser?):

Using iPhone 7 Plus/iOS 12.1.2 on Mobile Safari, there are some elements that still have their default browser styles. Open your test page at 
https://nicolas-cusan.github.io/destyle.css/test.html and find the following elements by what’s contained in their content (viewing the source of the page is a challenge without my laptop):

- Said no one, ever.
- Definition List Title
- Table Heading 1 (through 5)
- Table Footer 1 (through 5)
- Keyboard input: Cmd
- Inline code: `<div>code</div>`
- Sample output: This is sample output from a computer program.
- Pre-formatted text
P R E F O R M A T T E D T E X T
  ! " # $ % & ' ( ) * + , - . /
  0 1 2 3 4 5 6 7 8 9 : ; < = > ?
  @ A B C D E F G H I J K L M N O
  P Q R S T U V W X Y Z [ \ ] ^ _
  ` a b c d e f g h i j k l m n o
  p q r s t u v w x y z { | } ~ 
- Strong is used to indicate strong importance.
- This text has added emphasis.
- The b element is stylistically different text from normal text, without any special importance.
- The i element is text that is offset from the normal text.
- The u element is text with an unarticulated, though explicitly rendered, non-textual annotation.
- This text is deleted and This text is inserted.
- This text has a strikethrough.
- Superscript®.
- Subscript for things like H2O.
- This small text is small for for fine print, etc.
- Abbreviation: HTML
- This text is a short inline quotation.
- This is a citation.
- The dfn element indicates a definition.
- The mark element indicates a highlight.
- The variable element, such as x = y.
- Canvas
- Meter
- Progress

I admit many of these use bold, italics, underline, strikethroughs, etc, but if you’re trying to remove ALL browser defaults, those particular elements are not de-styled. Also, if I remember correctly, the `canvas` element has a default width and height added by the browser (similar to the `iframe` element) and doesn’t do much until you activate it with JavaScript.

I hope these help. :)

**Comment by nicolas-cusan** [comment]
Hi @PickJBennett,

the purpose is not to overwrite ALL browser defaults but to prevent the usual overwriting needed when using other resets / normalizers and only _de-style_ where it makes the most sense.

As said in the [docs](https://github.com/nicolas-cusan/destyle.css#rules--caveats):

> - `code`, `pre`, `kbd`, `samp` maintain a monospaced font-family
> - Inline elements that carry style (`b`, `i`, `strong`, etc.) are not reset.

The reasoning is that the style these tags carry is usually the intended style when using them in HTML. If not it is easy to overwrite them globally.

Regarding `iframe` and `canvas`, I would not know what other size to give them but the default size as these element are rarely used without any styles applied to them and the default size is as good as any I could define for them. Setting the size to 0 is not advantageous in my opinion as it will make them invisible, wich I don't consider to be a good thing.

Anyway I will update the Readme to reflect:

- that `iframe` and `canvas` width and height are not changed 
- that HTML5 elements like `meter` and `progress` styles are not changed.

Thank you for your feedback, I really appreciate it!
