### ISSUE TITLE
contenteditable

### ISSUE THREAD

**Issue by KaKi87** [nicolas-cusan/destyle.css#11]
Hello,

First of all, I love the way of destyling instead of just normalizing, and I'm quite satisfied with your project, thanks.

However, I have an issue with `[contenteditable]` : it remains styled similarly to `input[type=text]`.

Thanks !

**Comment by nicolas-cusan** [comment]
Hi @KaKi87, thank you for using destyle.css I will take a look at the issue as soon as I have some time and come back to you.

**Comment by KaKi87** [comment]
Hey @nicolas-cusan, I actually found the fix :
```css
[contenteditable] {
    outline: none;
}
```
Thanks.

**Comment by nicolas-cusan** [comment]
All right I am gonna close this then.

**Comment by KaKi87** [comment]
I mean, could you add this to destyle.css ?

**Comment by nicolas-cusan** [comment]
@KaKi87 I thought you had fixed that in your project. After reviewing it I have added it to the library. Hope that helps!

**Comment by KaKi87** [comment]
Yes I did, but adding it to destyle.css allows to fix the default behavior. Thanks !
