### ISSUE TITLE
Style on inputs being overwritten by destyle.css

### ISSUE THREAD

**Issue by nagman** [nicolas-cusan/destyle.css#12]
Hi!
First of all thanks for this small package that I use systematically in all my projects :+1:
 
I've just updated `destyle.css` today, and now all my inputs have their borders removed :sob:

I've seen that you've changed the selector declaration for `input` 2 days ago, would it be the reason?

In my browser, I can see that the `destyle.css` styles for `input` take precedence over my styles (which use classes):

![image](https://user-images.githubusercontent.com/16116486/90274724-59529600-de61-11ea-9592-e562e797ad62.png)

So of course, I'm complaining about the `border`, but there are also other properties that are overwritten (border is just the most visibly obvious).

**Comment by nicolas-cusan** [comment]
@nagman I am glad you like it! The border thing is definitely not intended. I tried to remove checkboxes and radiobuttons from that ruleset but obviously it is now overqualified. I will take a look as soon as I can and make a new release.

**Comment by Maksiemens** [comment]
I have same effect

**Comment by nicolas-cusan** [comment]
@nagman @Maksiemens I made a new version that should fix the issue: https://github.com/nicolas-cusan/destyle.css/tree/v1.0.15 Otherwise let me know!

**Comment by nagman** [comment]
That's perfect, thanks a lot!
