### ISSUE TITLE
select[disabled]

### ISSUE THREAD

**Issue by KaKi87** [nicolas-cusan/destyle.css#15]
Hello,

Please have a look at [this fiddle](https://jsfiddle.net/9gcL1720/) in which `select[disabled]` is not destyled.

Thanks !

**Comment by nicolas-cusan** [comment]
Hi @KaKi87, what browser are you using? It looks destyled for me: 

<img width="624" alt="Screen Shot 2021-02-15 at 21 08 41" src="https://user-images.githubusercontent.com/1353931/107989204-0f926600-6fd2-11eb-9b4c-e20477c28860.png">

**Comment by KaKi87** [comment]
Well, I actually meant that the gray color should also be removed.

Like `input[disabled]`.

Thanks

**Comment by nicolas-cusan** [comment]
I see, I am not sure if this should be removed. I'll leave this issue open and think about it. Thank you for pointing it out.

**Comment by KaKi87** [comment]
If you don't want to destyle `select[disabled]`, then you would have, for consistency, to **re**style the following components :

- `option[disabled]`
- `button[disabled]`
- `textarea[disabled]`

However, this is against destyle **by definition**.

I use destyle precisely because I want to decide how to style myself, and that includes disabled inputs, all kind of those.

Thanks

**Comment by nicolas-cusan** [comment]
Well that is not true, destyle is, as the description says, "opinionated" and not everything is destyled (e.g. `<strong>`, `<i>`) see the [README here](https://github.com/nicolas-cusan/destyle.css#rules).

Consistency is not really important here, removing the bits that I do not want to overwrite every time when styling an element is the important thing and I have never run into an issue with disabled selects.

As said, I will think about this.

**Comment by KaKi87** [comment]
Well, semantically, `<b>` and `<i>` could stay styled while `<strong>` and `<em>` shouldn't.

**Comment by nicolas-cusan** [comment]
Closed via #19
