### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by SineYlo** [nicolas-cusan/destyle.css#21]
Hi!
I didn't know where else to write, so I decided here. Is there any way I can contact you by mail? There are some suggestions for improvement.

**Comment by nicolas-cusan** [comment]
@SineYlo thank you for opening the issue. Feel free to address any suggestions here. Thank you!

**Comment by SineYlo** [comment]
I have created an interesting reset implementation using classes and mixins. I would like to show you. Should I make a pull request, or how do I show it all?
