### ISSUE TITLE
[Question] scrollbar appearing on flex column header/footer/template when combining destyle w/ other CSS

### ISSUE THREAD

**Issue by KaKi87** [nicolas-cusan/destyle.css#22]
Hello,

[Here](https://jsfiddle.net/s7z5qhj9/)'s a simple template containing :
- `body` (`display: flex`, `flex-direction: column`)
  - `header`
  - `main` (`flex: 1`)
  - `footer`
- [`destyle.css/destyle.min.css`](https://unpkg.com/destyle.css@3.0.2/destyle.min.css)
- [`brands.css/Discord.css`](https://rawcdn.githack.com/KaKi87/brands.css/473858ec2e3c148039ea5ac173d1ae668f8e33a2/Discord/Discord.css)

A scrollbar appears, but disappears when either removing the second stylesheet or adding `line-height: normal` to `body`.

Any idea why ?

Thanks

**Comment by nicolas-cusan** [comment]
It seems to have something to do with the `font-family` on the `body` in the `Discord.css` stylesheet. But I am not sure why that is... it is indeed strange.

It seems that the `Whitney` font that is bundled with macOS (I am on macOS) some how messes with the size of the elements.

Maybe you can try to actually load the font files (it seems that the path in the `@font-face` declarations does not link to anything) and that might fix it.

**Comment by KaKi87** [comment]
I am not on Mac but on Linux, and I don't have the Whitney font installed, yet the font is loading and I am experiencing this issue.

The `@font-face` declarations work because those WOFF files exist in the same [directory](https://git.kaki87.net/KaKi87/brands.css/src/branch/master/Discord) as this CSS file.

The issue is indeed due to the combination of `font-family: 'Whitney', sans-serif` from `Discord.css` and `line-height: 1.15` from `destyle.min.css`.

Why does Destyle include this, though ?

Thanks

**Comment by nicolas-cusan** [comment]
I like `line-height: 1.15` as a default for line-height but removing it does not seem to fix the issue for me.
