### ISSUE TITLE
[Feature request] Remove user agent minimal widths

### ISSUE THREAD

**Issue by KaKi87** [nicolas-cusan/destyle.css#23]
Hi,

Browsers apply minimal width by default on elements, preventing text wrapping and flex containers to behave properly, requiring the developer to add `min-width: 0`.

https://youtube.com/watch?v=cH8VbLM1958
https://defensivecss.dev/tip/flexbox-min-content-size/
https://www.joshwcomeau.com/css/interactive-guide-to-flexbox/

Therefore, it seems it would be a great default for destyle.css to remove these behaviors.

Thanks

**Comment by nicolas-cusan** [comment]
Hi @KaKi87 thanks for the input. Added it in v4.0.1
