### ISSUE TITLE
reset 'menu' padding and margin

### ISSUE THREAD

**Issue by pablocazorla** [nicolas-cusan/destyle.css#4]
I added menu{margin: 0; padding: 0;} to my code, because I need it.. What do you think, Nicolas?

**Comment by nicolas-cusan** [comment]
Hello @pablocazorla thank you for your input.

It seems menu is [not widely implemented](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#Browser_compatibility) in browsers. So for now I will leave it out.
