### ISSUE TITLE
Inherited border causes unexpected behaviors

### ISSUE THREAD

**Issue by bluemoehre** [nicolas-cusan/destyle.css#7]
I noticed an issue with one style rule:

    button,
    input,
    optgroup,
    select,
    textarea {
      ...
      border: inherit;
      ...
    }

Imagine using one of these elements within any **container** having a **border**. It will get **inherited** which makes no sense.

I would recommend to set it to `border: none` or `border: 0`.

**Comment by nicolas-cusan** [comment]
Hi @bluemoehre, that seems right. I will change it. Thank you!

**Comment by nicolas-cusan** [comment]
Fixed: https://github.com/nicolas-cusan/destyle.css/releases/tag/1.0.11
