### ISSUE TITLE
Reset padding and margin in universal selector

### ISSUE THREAD

**Issue by vwkd** [nicolas-cusan/destyle.css#9]
While trying out destyle I found some left over paddings. They are small but still.

- In the `th` and `td` elements

![padding](https://user-images.githubusercontent.com/33468089/82128386-1bd76180-97bb-11ea-950e-f010bfa67f33.gif)

(example page from destyle)

- As well as in the `option` element

![paddingoption](https://user-images.githubusercontent.com/33468089/82128632-e16ec400-97bc-11ea-8e20-632a429d989d.gif)

(example page [html5-kitchen-sink](https://github.com/dbox/html5-kitchen-sink))

I think it would be a good idea to reset the `padding` in the universal selector. This way no elements can be missed. Also `margin` could be reset like this as well, assuming its equally desired to be reset for all elements. This would also deduplicate quite a bit of code, as right now they are reset individually for every element.

I'm happy to put up an PR if this is accepted.

**Comment by nicolas-cusan** [comment]
Hi @zjopy thank you for reporting the lack of reseting of `th`, `td` and `option`.

Using the universal selector sounds interesting and would, as you correctly point out, save some code.

For now I actually like the explicitness of resetting only what is necessary for each element. 

I can not guarantee that I would accept a PR using the universal selector without seeing the code first but I would surely have a look and consider accepting it. 

In any case I will include styles to reset `th`, `td` and `option` shortly.

**Comment by vwkd** [comment]
Thanks for replying. I'll put up a PR so you can take a look at it.

I agree that being explicit is good, especially if you want to reset it only for certain elements. Also I can understand if the wish is to document exactly what elements are reset for information purposes.

I figured since `padding` and `margin` are properties that are reset for all elements, the assurance gained that there are no elements left that haven't yet been reset was may be worth giving up on the explicit details in favor of the general approach.

I put up the PR so you can decide there.
